version: 2
jobs:
  build:
    docker:
      - image: vuejs/ci
    steps:
      - checkout
      - run:
          name: preprocess-clean-node-modules
          command: rm -rf node_modules
      - run:
          name: preprocess-npm-install
          command: npm install
      - run:
          name: lint
          command: npm run lint
